version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432

  worker:
    image: "chazari/balance_checker:latest"
    restart: always
    depends_on:
      - postgres